blank_issues_enabled: false
contact_links:
  - name: Ask a question in Discussions
    url: https://github.com/Enggvault
    about: Ask the community for help in GitHub Discussions.
  - name: Join our Discord
    url: https://discord.gg/g467F3xBeQ
    about: Chat with other developers and the core team.
  - name: EnggVault Security Policy
    url: https://github.com/Enggvault/.github/blob/main/SECURITY.md
    about: Learn how to report a security vulnerability.
